version: "2"

linters:
  default: standard
  settings:
    errcheck:
      # Don't check error returns for these functions
      exclude-functions:
        - fmt.Fprintf
        - (*database/sql.Rows).Close

issues:
  exclude-files:
    # Exclude generated xo files from linting
    - ".*\\.xo\\.go$"
