package xomodels

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Message represents a row from 'messages'.
type Message struct {
	ID         string `json:"id"`          // id
	RoomID     string `json:"room_id"`     // room_id
	UserID     string `json:"user_id"`     // user_id
	Body       string `json:"body"`        // body
	CreatedAt  Time   `json:"created_at"`  // created_at
	ModifiedAt Time   `json:"modified_at"` // modified_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Message] exists in the database.
func (m *Message) Exists() bool {
	return m._exists
}

// Deleted returns true when the [Message] has been marked for deletion
// from the database.
func (m *Message) Deleted() bool {
	return m._deleted
}

// Insert inserts the [Message] to the database.
func (m *Message) Insert(ctx context.Context, db DB) error {
	switch {
	case m._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case m._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO messages (` +
		`id, room_id, user_id, body, created_at, modified_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)`
	// run
	logf(sqlstr, m.ID, m.RoomID, m.UserID, m.Body, m.CreatedAt, m.ModifiedAt)
	if _, err := db.ExecContext(ctx, sqlstr, m.ID, m.RoomID, m.UserID, m.Body, m.CreatedAt, m.ModifiedAt); err != nil {
		return logerror(err)
	}
	// set exists
	m._exists = true
	return nil
}

// Update updates a [Message] in the database.
func (m *Message) Update(ctx context.Context, db DB) error {
	switch {
	case !m._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case m._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE messages SET ` +
		`room_id = $1, user_id = $2, body = $3, created_at = $4, modified_at = $5 ` +
		`WHERE id = $6`
	// run
	logf(sqlstr, m.RoomID, m.UserID, m.Body, m.CreatedAt, m.ModifiedAt, m.ID)
	if _, err := db.ExecContext(ctx, sqlstr, m.RoomID, m.UserID, m.Body, m.CreatedAt, m.ModifiedAt, m.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Message] to the database.
func (m *Message) Save(ctx context.Context, db DB) error {
	if m.Exists() {
		return m.Update(ctx, db)
	}
	return m.Insert(ctx, db)
}

// Upsert performs an upsert for [Message].
func (m *Message) Upsert(ctx context.Context, db DB) error {
	switch {
	case m._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO messages (` +
		`id, room_id, user_id, body, created_at, modified_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`room_id = EXCLUDED.room_id, user_id = EXCLUDED.user_id, body = EXCLUDED.body, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at `
	// run
	logf(sqlstr, m.ID, m.RoomID, m.UserID, m.Body, m.CreatedAt, m.ModifiedAt)
	if _, err := db.ExecContext(ctx, sqlstr, m.ID, m.RoomID, m.UserID, m.Body, m.CreatedAt, m.ModifiedAt); err != nil {
		return logerror(err)
	}
	// set exists
	m._exists = true
	return nil
}

// Delete deletes the [Message] from the database.
func (m *Message) Delete(ctx context.Context, db DB) error {
	switch {
	case !m._exists: // doesn't exist
		return nil
	case m._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM messages ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, m.ID)
	if _, err := db.ExecContext(ctx, sqlstr, m.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	m._deleted = true
	return nil
}

// MessageByID retrieves a row from 'messages' as a [Message].
//
// Generated from index 'sqlite_autoindex_messages_1'.
func MessageByID(ctx context.Context, db DB, id string) (*Message, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, room_id, user_id, body, created_at, modified_at ` +
		`FROM messages ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	m := Message{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&m.ID, &m.RoomID, &m.UserID, &m.Body, &m.CreatedAt, &m.ModifiedAt); err != nil {
		return nil, logerror(err)
	}
	return &m, nil
}

// Room returns the Room associated with the [Message]'s (RoomID).
//
// Generated from foreign key 'messages_room_id_fkey'.
func (m *Message) Room(ctx context.Context, db DB) (*Room, error) {
	return RoomByID(ctx, db, m.RoomID)
}

// User returns the User associated with the [Message]'s (UserID).
//
// Generated from foreign key 'messages_user_id_fkey'.
func (m *Message) User(ctx context.Context, db DB) (*User, error) {
	return UserByID(ctx, db, m.UserID)
}
