package xomodels

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// RoomMember represents a row from 'room_members'.
type RoomMember struct {
	UserID string `json:"user_id"` // user_id
	RoomID string `json:"room_id"` // room_id
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [RoomMember] exists in the database.
func (rm *RoomMember) Exists() bool {
	return rm._exists
}

// Deleted returns true when the [RoomMember] has been marked for deletion
// from the database.
func (rm *RoomMember) Deleted() bool {
	return rm._deleted
}

// Insert inserts the [RoomMember] to the database.
func (rm *RoomMember) Insert(ctx context.Context, db DB) error {
	switch {
	case rm._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case rm._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO room_members (` +
		`user_id, room_id` +
		`) VALUES (` +
		`$1, $2` +
		`)`
	// run
	logf(sqlstr, rm.UserID, rm.RoomID)
	if _, err := db.ExecContext(ctx, sqlstr, rm.UserID, rm.RoomID); err != nil {
		return logerror(err)
	}
	// set exists
	rm._exists = true
	return nil
}

// ------ NOTE: Update statements omitted due to lack of fields other than primary key ------

// Delete deletes the [RoomMember] from the database.
func (rm *RoomMember) Delete(ctx context.Context, db DB) error {
	switch {
	case !rm._exists: // doesn't exist
		return nil
	case rm._deleted: // deleted
		return nil
	}
	// delete with composite primary key
	const sqlstr = `DELETE FROM room_members ` +
		`WHERE user_id = $1 AND room_id = $2`
	// run
	logf(sqlstr, rm.UserID, rm.RoomID)
	if _, err := db.ExecContext(ctx, sqlstr, rm.UserID, rm.RoomID); err != nil {
		return logerror(err)
	}
	// set deleted
	rm._deleted = true
	return nil
}

// RoomMemberByUserIDRoomID retrieves a row from 'room_members' as a [RoomMember].
//
// Generated from index 'sqlite_autoindex_room_members_1'.
func RoomMemberByUserIDRoomID(ctx context.Context, db DB, userID, roomID string) (*RoomMember, error) {
	// query
	const sqlstr = `SELECT ` +
		`user_id, room_id ` +
		`FROM room_members ` +
		`WHERE user_id = $1 AND room_id = $2`
	// run
	logf(sqlstr, userID, roomID)
	rm := RoomMember{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, userID, roomID).Scan(&rm.UserID, &rm.RoomID); err != nil {
		return nil, logerror(err)
	}
	return &rm, nil
}

// Room returns the Room associated with the [RoomMember]'s (RoomID).
//
// Generated from foreign key 'room_members_room_id_fkey'.
func (rm *RoomMember) Room(ctx context.Context, db DB) (*Room, error) {
	return RoomByID(ctx, db, rm.RoomID)
}

// User returns the User associated with the [RoomMember]'s (UserID).
//
// Generated from foreign key 'room_members_user_id_fkey'.
func (rm *RoomMember) User(ctx context.Context, db DB) (*User, error) {
	return UserByID(ctx, db, rm.UserID)
}
