package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// DefaultRoom represents a row from 'default_room'.
type DefaultRoom struct {
	ID string `json:"id"` // id
}

// GetDefaultRoom runs a custom query, returning results as [DefaultRoom].
func GetDefaultRoom(ctx context.Context, db DB) (*DefaultRoom, error) {
	// query
	const sqlstr = `SELECT ID AS id ` +
		`FROM rooms r ` +
		`WHERE r.is_default`
	// run
	logf(sqlstr)
	var dr DefaultRoom
	if err := db.QueryRowContext(ctx, sqlstr).Scan(&dr.ID); err != nil {
		return nil, logerror(err)
	}
	return &dr, nil
}
