package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// ListUsers represents a row from 'list_users'.
type ListUsers struct {
	ID          string `json:"id"`           // id
	Username    string `json:"username"`     // username
	DisplayName string `json:"display_name"` // display_name
	Avatar      string `json:"avatar"`       // avatar
}

// ListUsersByQueryExcludeUserIDLimit runs a custom query, returning results as [ListUsers].
func ListUsersByQueryExcludeUserIDLimit(ctx context.Context, db DB, query, excludeUserID string, limit int) ([]*ListUsers, error) {
	// query
	const sqlstr = `SELECT u.id, u.username, u.display_name, COALESCE(u.avatar, '') as avatar ` +
		`FROM users u ` +
		`WHERE u.username LIKE $1 AND u.id != $2 ` +
		`ORDER BY u.username ` +
		`LIMIT $3`
	// run
	logf(sqlstr, query, excludeUserID, limit)
	rows, err := db.QueryContext(ctx, sqlstr, query, excludeUserID, limit)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*ListUsers
	for rows.Next() {
		var lu ListUsers
		// scan
		if err := rows.Scan(&lu.ID, &lu.Username, &lu.DisplayName, &lu.Avatar); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &lu)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
