package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// Reaction represents a row from 'reactions'.
type Reaction struct {
	MessageID string `json:"message_id"` // message_id
	UserID    string `json:"user_id"`    // user_id
	Emoji     string `json:"emoji"`      // emoji
	CreatedAt string `json:"created_at"` // created_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Reaction] exists in the database.
func (r *Reaction) Exists() bool {
	return r._exists
}

// Deleted returns true when the [Reaction] has been marked for deletion
// from the database.
func (r *Reaction) Deleted() bool {
	return r._deleted
}

// Insert inserts the [Reaction] to the database.
func (r *Reaction) Insert(ctx context.Context, db DB) error {
	switch {
	case r._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case r._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO reactions (` +
		`message_id, user_id, emoji, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`
	// run
	logf(sqlstr, r.MessageID, r.UserID, r.Emoji, r.CreatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, r.MessageID, r.UserID, r.Emoji, r.CreatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Update updates a [Reaction] in the database.
func (r *Reaction) Update(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case r._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE reactions SET ` +
		`created_at = $1 ` +
		`WHERE message_id = $2 AND user_id = $3 AND emoji = $4`
	// run
	logf(sqlstr, r.CreatedAt, r.MessageID, r.UserID, r.Emoji)
	if _, err := db.ExecContext(ctx, sqlstr, r.CreatedAt, r.MessageID, r.UserID, r.Emoji); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Reaction] to the database.
func (r *Reaction) Save(ctx context.Context, db DB) error {
	if r.Exists() {
		return r.Update(ctx, db)
	}
	return r.Insert(ctx, db)
}

// Upsert performs an upsert for [Reaction].
func (r *Reaction) Upsert(ctx context.Context, db DB) error {
	switch {
	case r._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO reactions (` +
		`message_id, user_id, emoji, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)` +
		` ON CONFLICT (message_id, user_id, emoji) DO ` +
		`UPDATE SET ` +
		`created_at = EXCLUDED.created_at `
	// run
	logf(sqlstr, r.MessageID, r.UserID, r.Emoji, r.CreatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, r.MessageID, r.UserID, r.Emoji, r.CreatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Delete deletes the [Reaction] from the database.
func (r *Reaction) Delete(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return nil
	case r._deleted: // deleted
		return nil
	}
	// delete with composite primary key
	const sqlstr = `DELETE FROM reactions ` +
		`WHERE message_id = $1 AND user_id = $2 AND emoji = $3`
	// run
	logf(sqlstr, r.MessageID, r.UserID, r.Emoji)
	if _, err := db.ExecContext(ctx, sqlstr, r.MessageID, r.UserID, r.Emoji); err != nil {
		return logerror(err)
	}
	// set deleted
	r._deleted = true
	return nil
}

// ReactionsByMessageID retrieves a row from 'reactions' as a [Reaction].
//
// Generated from index 'reactions_message'.
func ReactionsByMessageID(ctx context.Context, db DB, messageID string) ([]*Reaction, error) {
	// query
	const sqlstr = `SELECT ` +
		`message_id, user_id, emoji, created_at ` +
		`FROM reactions ` +
		`WHERE message_id = $1`
	// run
	logf(sqlstr, messageID)
	rows, err := db.QueryContext(ctx, sqlstr, messageID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*Reaction
	for rows.Next() {
		r := Reaction{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&r.MessageID, &r.UserID, &r.Emoji, &r.CreatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &r)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// ReactionByMessageIDUserIDEmoji retrieves a row from 'reactions' as a [Reaction].
//
// Generated from index 'sqlite_autoindex_reactions_1'.
func ReactionByMessageIDUserIDEmoji(ctx context.Context, db DB, messageID, userID, emoji string) (*Reaction, error) {
	// query
	const sqlstr = `SELECT ` +
		`message_id, user_id, emoji, created_at ` +
		`FROM reactions ` +
		`WHERE message_id = $1 AND user_id = $2 AND emoji = $3`
	// run
	logf(sqlstr, messageID, userID, emoji)
	r := Reaction{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, messageID, userID, emoji).Scan(&r.MessageID, &r.UserID, &r.Emoji, &r.CreatedAt); err != nil {
		return nil, logerror(err)
	}
	return &r, nil
}

// Message returns the Message associated with the [Reaction]'s (MessageID).
//
// Generated from foreign key 'reactions_message_id_fkey'.
func (r *Reaction) Message(ctx context.Context, db DB) (*Message, error) {
	return MessageByID(ctx, db, r.MessageID)
}

// User returns the User associated with the [Reaction]'s (UserID).
//
// Generated from foreign key 'reactions_user_id_fkey'.
func (r *Reaction) User(ctx context.Context, db DB) (*User, error) {
	return UserByID(ctx, db, r.UserID)
}
