package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// ReadPosition represents a row from 'read_positions'.
type ReadPosition struct {
	UserID     string `json:"user_id"`      // user_id
	RoomID     string `json:"room_id"`      // room_id
	LastReadAt string `json:"last_read_at"` // last_read_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [ReadPosition] exists in the database.
func (rp *ReadPosition) Exists() bool {
	return rp._exists
}

// Deleted returns true when the [ReadPosition] has been marked for deletion
// from the database.
func (rp *ReadPosition) Deleted() bool {
	return rp._deleted
}

// Insert inserts the [ReadPosition] to the database.
func (rp *ReadPosition) Insert(ctx context.Context, db DB) error {
	switch {
	case rp._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case rp._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO read_positions (` +
		`user_id, room_id, last_read_at` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)`
	// run
	logf(sqlstr, rp.UserID, rp.RoomID, rp.LastReadAt)
	if _, err := db.ExecContext(ctx, sqlstr, rp.UserID, rp.RoomID, rp.LastReadAt); err != nil {
		return logerror(err)
	}
	// set exists
	rp._exists = true
	return nil
}

// Update updates a [ReadPosition] in the database.
func (rp *ReadPosition) Update(ctx context.Context, db DB) error {
	switch {
	case !rp._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case rp._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE read_positions SET ` +
		`last_read_at = $1 ` +
		`WHERE user_id = $2 AND room_id = $3`
	// run
	logf(sqlstr, rp.LastReadAt, rp.UserID, rp.RoomID)
	if _, err := db.ExecContext(ctx, sqlstr, rp.LastReadAt, rp.UserID, rp.RoomID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [ReadPosition] to the database.
func (rp *ReadPosition) Save(ctx context.Context, db DB) error {
	if rp.Exists() {
		return rp.Update(ctx, db)
	}
	return rp.Insert(ctx, db)
}

// Upsert performs an upsert for [ReadPosition].
func (rp *ReadPosition) Upsert(ctx context.Context, db DB) error {
	switch {
	case rp._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO read_positions (` +
		`user_id, room_id, last_read_at` +
		`) VALUES (` +
		`$1, $2, $3` +
		`)` +
		` ON CONFLICT (user_id, room_id) DO ` +
		`UPDATE SET ` +
		`last_read_at = EXCLUDED.last_read_at `
	// run
	logf(sqlstr, rp.UserID, rp.RoomID, rp.LastReadAt)
	if _, err := db.ExecContext(ctx, sqlstr, rp.UserID, rp.RoomID, rp.LastReadAt); err != nil {
		return logerror(err)
	}
	// set exists
	rp._exists = true
	return nil
}

// Delete deletes the [ReadPosition] from the database.
func (rp *ReadPosition) Delete(ctx context.Context, db DB) error {
	switch {
	case !rp._exists: // doesn't exist
		return nil
	case rp._deleted: // deleted
		return nil
	}
	// delete with composite primary key
	const sqlstr = `DELETE FROM read_positions ` +
		`WHERE user_id = $1 AND room_id = $2`
	// run
	logf(sqlstr, rp.UserID, rp.RoomID)
	if _, err := db.ExecContext(ctx, sqlstr, rp.UserID, rp.RoomID); err != nil {
		return logerror(err)
	}
	// set deleted
	rp._deleted = true
	return nil
}

// ReadPositionByUserIDRoomID retrieves a row from 'read_positions' as a [ReadPosition].
//
// Generated from index 'sqlite_autoindex_read_positions_1'.
func ReadPositionByUserIDRoomID(ctx context.Context, db DB, userID, roomID string) (*ReadPosition, error) {
	// query
	const sqlstr = `SELECT ` +
		`user_id, room_id, last_read_at ` +
		`FROM read_positions ` +
		`WHERE user_id = $1 AND room_id = $2`
	// run
	logf(sqlstr, userID, roomID)
	rp := ReadPosition{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, userID, roomID).Scan(&rp.UserID, &rp.RoomID, &rp.LastReadAt); err != nil {
		return nil, logerror(err)
	}
	return &rp, nil
}

// Room returns the Room associated with the [ReadPosition]'s (RoomID).
//
// Generated from foreign key 'read_positions_room_id_fkey'.
func (rp *ReadPosition) Room(ctx context.Context, db DB) (*Room, error) {
	return RoomByID(ctx, db, rp.RoomID)
}

// User returns the User associated with the [ReadPosition]'s (UserID).
//
// Generated from foreign key 'read_positions_user_id_fkey'.
func (rp *ReadPosition) User(ctx context.Context, db DB) (*User, error) {
	return UserByID(ctx, db, rp.UserID)
}
