package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// RoomMembers represents a row from 'room_members'.
type RoomMembers struct {
	ID          string `json:"id"`           // id
	Username    string `json:"username"`     // username
	DisplayName string `json:"display_name"` // display_name
	Avatar      string `json:"avatar"`       // avatar
}

// RoomMembersByRoomID runs a custom query, returning results as [RoomMembers].
func RoomMembersByRoomID(ctx context.Context, db DB, roomID string) ([]*RoomMembers, error) {
	// query
	const sqlstr = `SELECT u.id, u.username, u.display_name, COALESCE(u.avatar, '') as avatar ` +
		`FROM users u ` +
		`JOIN rooms_members rm ON u.id = rm.user_id ` +
		`WHERE rm.room_id = $1 ` +
		`ORDER BY u.username`
	// run
	logf(sqlstr, roomID)
	rows, err := db.QueryContext(ctx, sqlstr, roomID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*RoomMembers
	for rows.Next() {
		var rm RoomMembers
		// scan
		if err := rows.Scan(&rm.ID, &rm.Username, &rm.DisplayName, &rm.Avatar); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &rm)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
