package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Rooms represents a row from 'rooms'.
type Rooms struct {
	RoomID string `json:"room_id"` // room_id
}

// RoomsByUserID runs a custom query, returning results as [Rooms].
func RoomsByUserID(ctx context.Context, db DB, userID string) ([]*Rooms, error) {
	// query
	const sqlstr = `SELECT room_id ` +
		`FROM rooms_members ` +
		`WHERE user_id = $1`
	// run
	logf(sqlstr, userID)
	rows, err := db.QueryContext(ctx, sqlstr, userID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*Rooms
	for rows.Next() {
		var r Rooms
		// scan
		if err := rows.Scan(&r.RoomID); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &r)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
