package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// RoomMessagesFirstPage represents a row from 'room_messages_first_page'.
type RoomMessagesFirstPage struct {
	ID         string `json:"id"`          // id
	RoomID     string `json:"room_id"`     // room_id
	UserID     string `json:"user_id"`     // user_id
	Body       string `json:"body"`        // body
	CreatedAt  string `json:"created_at"`  // created_at
	ModifiedAt string `json:"modified_at"` // modified_at
	Username   string `json:"username"`    // username
}

// RoomMessagesFirstPagesByRoomIDLimit runs a custom query, returning results as [RoomMessagesFirstPage].
func RoomMessagesFirstPagesByRoomIDLimit(ctx context.Context, db DB, roomID string, limit int) ([]*RoomMessagesFirstPage, error) {
	// query
	const sqlstr = `SELECT m.id, m.room_id, m.user_id, m.body, m.created_at, m.modified_at, u.username ` +
		`FROM messages m ` +
		`JOIN users u ON m.user_id = u.id ` +
		`WHERE m.room_id = $1 ` +
		`ORDER BY m.created_at DESC ` +
		`LIMIT $2`
	// run
	logf(sqlstr, roomID, limit)
	rows, err := db.QueryContext(ctx, sqlstr, roomID, limit)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*RoomMessagesFirstPage
	for rows.Next() {
		var rmfp RoomMessagesFirstPage
		// scan
		if err := rows.Scan(&rmfp.ID, &rmfp.RoomID, &rmfp.UserID, &rmfp.Body, &rmfp.CreatedAt, &rmfp.ModifiedAt, &rmfp.Username); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &rmfp)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
