package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// RoomMemberCount represents a row from 'room_member_count'.
type RoomMemberCount struct {
	Count string `json:"count"` // count
}

// RoomMemberCountByRoomID runs a custom query, returning results as [RoomMemberCount].
func RoomMemberCountByRoomID(ctx context.Context, db DB, roomID string) (*RoomMemberCount, error) {
	// query
	const sqlstr = `SELECT COUNT(*) AS count ` +
		`FROM rooms_members ` +
		`WHERE room_id = $1`
	// run
	logf(sqlstr, roomID)
	var rmc RoomMemberCount
	if err := db.QueryRowContext(ctx, sqlstr, roomID).Scan(&rmc.Count); err != nil {
		return nil, logerror(err)
	}
	return &rmc, nil
}
