package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// Room represents a row from 'rooms'.
type Room struct {
	ID        string `json:"id"`         // id
	Name      string `json:"name"`       // name
	IsPrivate bool   `json:"is_private"` // is_private
	IsDefault bool   `json:"is_default"` // is_default
	CreatedAt Time   `json:"created_at"` // created_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Room] exists in the database.
func (r *Room) Exists() bool {
	return r._exists
}

// Deleted returns true when the [Room] has been marked for deletion
// from the database.
func (r *Room) Deleted() bool {
	return r._deleted
}

// Insert inserts the [Room] to the database.
func (r *Room) Insert(ctx context.Context, db DB) error {
	switch {
	case r._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case r._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO rooms (` +
		`id, name, is_private, is_default, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`)`
	// run
	logf(sqlstr, r.ID, r.Name, r.IsPrivate, r.IsDefault, r.CreatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID, r.Name, r.IsPrivate, r.IsDefault, r.CreatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Update updates a [Room] in the database.
func (r *Room) Update(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case r._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE rooms SET ` +
		`name = $1, is_private = $2, is_default = $3, created_at = $4 ` +
		`WHERE id = $5`
	// run
	logf(sqlstr, r.Name, r.IsPrivate, r.IsDefault, r.CreatedAt, r.ID)
	if _, err := db.ExecContext(ctx, sqlstr, r.Name, r.IsPrivate, r.IsDefault, r.CreatedAt, r.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Room] to the database.
func (r *Room) Save(ctx context.Context, db DB) error {
	if r.Exists() {
		return r.Update(ctx, db)
	}
	return r.Insert(ctx, db)
}

// Upsert performs an upsert for [Room].
func (r *Room) Upsert(ctx context.Context, db DB) error {
	switch {
	case r._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO rooms (` +
		`id, name, is_private, is_default, created_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`name = EXCLUDED.name, is_private = EXCLUDED.is_private, is_default = EXCLUDED.is_default, created_at = EXCLUDED.created_at `
	// run
	logf(sqlstr, r.ID, r.Name, r.IsPrivate, r.IsDefault, r.CreatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID, r.Name, r.IsPrivate, r.IsDefault, r.CreatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Delete deletes the [Room] from the database.
func (r *Room) Delete(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return nil
	case r._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM rooms ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, r.ID)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	r._deleted = true
	return nil
}

// RoomByID retrieves a row from 'rooms' as a [Room].
//
// Generated from index 'sqlite_autoindex_rooms_1'.
func RoomByID(ctx context.Context, db DB, id string) (*Room, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, name, is_private, is_default, created_at ` +
		`FROM rooms ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	r := Room{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&r.ID, &r.Name, &r.IsPrivate, &r.IsDefault, &r.CreatedAt); err != nil {
		return nil, logerror(err)
	}
	return &r, nil
}
