package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// User represents a row from 'users'.
type User struct {
	ID         string         `json:"id"`          // id
	Username   string         `json:"username"`    // username
	Password   string         `json:"password"`    // password
	Active     sql.NullInt64  `json:"active"`      // active
	Avatar     sql.NullString `json:"avatar"`      // avatar
	LastRoom   string         `json:"last_room"`   // last_room
	CreatedAt  string         `json:"created_at"`  // created_at
	ModifiedAt string         `json:"modified_at"` // modified_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [User] exists in the database.
func (u *User) Exists() bool {
	return u._exists
}

// Deleted returns true when the [User] has been marked for deletion
// from the database.
func (u *User) Deleted() bool {
	return u._deleted
}

// Insert inserts the [User] to the database.
func (u *User) Insert(ctx context.Context, db DB) error {
	switch {
	case u._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case u._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (manual)
	const sqlstr = `INSERT INTO users (` +
		`id, username, password, active, avatar, last_room, created_at, modified_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)`
	// run
	logf(sqlstr, u.ID, u.Username, u.Password, u.Active, u.Avatar, u.LastRoom, u.CreatedAt, u.ModifiedAt)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID, u.Username, u.Password, u.Active, u.Avatar, u.LastRoom, u.CreatedAt, u.ModifiedAt); err != nil {
		return logerror(err)
	}
	// set exists
	u._exists = true
	return nil
}

// Update updates a [User] in the database.
func (u *User) Update(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case u._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE users SET ` +
		`username = $1, password = $2, active = $3, avatar = $4, last_room = $5, created_at = $6, modified_at = $7 ` +
		`WHERE id = $8`
	// run
	logf(sqlstr, u.Username, u.Password, u.Active, u.Avatar, u.LastRoom, u.CreatedAt, u.ModifiedAt, u.ID)
	if _, err := db.ExecContext(ctx, sqlstr, u.Username, u.Password, u.Active, u.Avatar, u.LastRoom, u.CreatedAt, u.ModifiedAt, u.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [User] to the database.
func (u *User) Save(ctx context.Context, db DB) error {
	if u.Exists() {
		return u.Update(ctx, db)
	}
	return u.Insert(ctx, db)
}

// Upsert performs an upsert for [User].
func (u *User) Upsert(ctx context.Context, db DB) error {
	switch {
	case u._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO users (` +
		`id, username, password, active, avatar, last_room, created_at, modified_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`username = EXCLUDED.username, password = EXCLUDED.password, active = EXCLUDED.active, avatar = EXCLUDED.avatar, last_room = EXCLUDED.last_room, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at `
	// run
	logf(sqlstr, u.ID, u.Username, u.Password, u.Active, u.Avatar, u.LastRoom, u.CreatedAt, u.ModifiedAt)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID, u.Username, u.Password, u.Active, u.Avatar, u.LastRoom, u.CreatedAt, u.ModifiedAt); err != nil {
		return logerror(err)
	}
	// set exists
	u._exists = true
	return nil
}

// Delete deletes the [User] from the database.
func (u *User) Delete(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return nil
	case u._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM users ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, u.ID)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	u._deleted = true
	return nil
}

// UserByID retrieves a row from 'users' as a [User].
//
// Generated from index 'sqlite_autoindex_users_1'.
func UserByID(ctx context.Context, db DB, id string) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, username, password, active, avatar, last_room, created_at, modified_at ` +
		`FROM users ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	u := User{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&u.ID, &u.Username, &u.Password, &u.Active, &u.Avatar, &u.LastRoom, &u.CreatedAt, &u.ModifiedAt); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}

// UserByUsername retrieves a row from 'users' as a [User].
//
// Generated from index 'users_username'.
func UserByUsername(ctx context.Context, db DB, username string) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, username, password, active, avatar, last_room, created_at, modified_at ` +
		`FROM users ` +
		`WHERE username = $1`
	// run
	logf(sqlstr, username)
	u := User{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, username).Scan(&u.ID, &u.Username, &u.Password, &u.Active, &u.Avatar, &u.LastRoom, &u.CreatedAt, &u.ModifiedAt); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}
