package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// UserRoomDetails represents a row from 'user_room_details'.
type UserRoomDetails struct {
	ID        string `json:"id"`         // id
	Name      string `json:"name"`       // name
	IsPrivate int    `json:"is_private"` // is_private
}

// UserRoomDetailsByUserID runs a custom query, returning results as [UserRoomDetails].
func UserRoomDetailsByUserID(ctx context.Context, db DB, userID string) ([]*UserRoomDetails, error) {
	// query
	const sqlstr = `SELECT r.id, r.name, r.is_private ` +
		`FROM rooms r ` +
		`JOIN rooms_members rm ON r.id = rm.room_id ` +
		`WHERE rm.user_id = $1 ` +
		`ORDER BY r.name`
	// run
	logf(sqlstr, userID)
	rows, err := db.QueryContext(ctx, sqlstr, userID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*UserRoomDetails
	for rows.Next() {
		var urd UserRoomDetails
		// scan
		if err := rows.Scan(&urd.ID, &urd.Name, &urd.IsPrivate); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &urd)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
