package models

// Code generated by dbtpl. DO NOT EDIT.

import (
	"context"
)

// UserDMs represents a row from 'user_d_ms'.
type UserDMs struct {
	ID            string `json:"id"`              // id
	Name          string `json:"name"`            // name
	RoomType      string `json:"room_type"`       // room_type
	IsPrivate     int    `json:"is_private"`      // is_private
	LastMessageAt string `json:"last_message_at"` // last_message_at
}

// UserDMsByUserID runs a custom query, returning results as [UserDMs].
func UserDMsByUserID(ctx context.Context, db DB, userID string) ([]*UserDMs, error) {
	// query
	const sqlstr = `SELECT r.id, r.name, r.room_type, r.is_private, COALESCE(r.last_message_at, '') as last_message_at ` +
		`FROM rooms r ` +
		`JOIN rooms_members rm ON r.id = rm.room_id ` +
		`WHERE rm.user_id = $1 AND r.room_type = 'dm' ` +
		`ORDER BY r.last_message_at DESC NULLS LAST, r.created_at DESC`
	// run
	logf(sqlstr, userID)
	rows, err := db.QueryContext(ctx, sqlstr, userID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*UserDMs
	for rows.Next() {
		var udm UserDMs
		// scan
		if err := rows.Scan(&udm.ID, &udm.Name, &udm.RoomType, &udm.IsPrivate, &udm.LastMessageAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &udm)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
