#!/usr/bin/env bash

RED='\e[31m'
RESET='\e[0m'

# remove xo-generated files from server/models. It's important to remove old
# models so we don't reference tables that dont' exist
grep -l "Code generated by xo" server/models/* | while IFS= read -r f; do
    printf "%bremoving %s%b\n" "$RED" "$f" "$RESET"
    rm "$f"
done

# remove the xo database if it exists, and create it from the schema
rm -f xo.db
sqlite3 'xo.db' < schema.sql

# generate models from the schema
xo -v schema sqlite://xo.db -o server/models

# generate custom queries
xo query sqlite://xo.db -M -B -2 -1 -o server/models -T DefaultRoom <<SQL
SELECT ID AS id
FROM rooms r
WHERE r.is_default
SQL

xo query sqlite://xo.db -M -B -2 -o server/models -T Rooms <<SQL
SELECT room_id
FROM rooms_members
WHERE user_id = %%userID string%%
SQL

# remove the xo database
rm xo.db
